author: codeskyblue
description: '...'
os: darwin linux windows
includes:
  - README.md
  - LICENSE
  - templates
excludes:
  - \.git
  - bindata.go
prepare:
  - go get github.com/jteeuwen/go-bindata/...
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash
  - nvm install node && nvm alias default node
  - npm config set registry http://registry.npmjs.org/
  - npm config set strict-ssl false
  - npm install -g webpack
  - npm install
  - make bundle
script:
  - go get -u github.com/jteeuwen/go-bindata/...
  - make binary
